apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-secret
  namespace: kube-system
spec:
  refreshInterval: 5h

  secretStoreRef:
    kind: ClusterSecretStore
    name: parameterstore

  target:
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: ebs-csi-driver-creds
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: aws-ebs-csi-driver
  namespace: kube-system
spec:
  releaseName: aws-ebs-csi-driver
  targetNamespace: kube-system
  interval: 24h
  chart:
    spec:
      chart: aws-ebs-csi-driver
      version: "2.28.x"
      sourceRef:
        kind: HelmRepository
        name: aws-ebs-csi-driver
        namespace: flux-system
      interval: 24h
