apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: container-registry-creds
  namespace: flux-system
spec:
  refreshInterval: 5h

  secretStoreRef:
    kind: ClusterSecretStore
    name: parameterstore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .value | toString }}"
    name: container-registry-creds
    creationPolicy: Owner
  data:
  - secretKey: value
    remoteRef:
      key: container-registry-creds
