apiVersion: v1
kind: Namespace
metadata:
  name: pgadmin4
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: runix
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.runix.net
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pgadmin4
  namespace: flux-system
spec:
  releaseName: pgadmin4
  targetNamespace: pgadmin4
  interval: 10m
  chart:
    spec:
      chart: pgadmin4
      version: "1.23.x"
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
      interval: 10m
  values:
    ingress:
      enabled: true
      hosts:
        - host: pg.olegkorsak.com
          paths:
            - path: /
              pathType: Prefix
    persistentVolume:
      enabled: true
      size: 1Gi
    existingSecret: pgadmin4-creds
    env:
      email: kamikaze.is.waiting.you@gmail.com
