apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: aws-for-fluent-bit
  namespace: kube-system
spec:
  chart:
    spec:
      chart: aws-for-fluent-bit
      version: "0.1.29" # Pinned version due to connectivity issues with CloudWatch
      sourceRef:
        kind: HelmRepository
        name: eks-charts
        namespace: flux-system
  interval: 1h
  values:
    clusterName: "eks-dev"
    cloudWatchLogs:
      region: "eu-north-1"
      logFormat: "json"
#      logKey: "log"
      logRetentionDays: 3
