apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: parameterstore
spec:
  provider:
    aws:
      service: ParameterStore
      role: arn:aws:iam::560733218776:role/external-secrets
      region: eu-west-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            namespace: terraform
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            namespace: terraform
            name: awssm-secret
            key: secret-access-key
