apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  refreshInterval: 5h

  secretStoreRef:
    kind: ClusterSecretStore
    name: parameterstore

  target:
    creationPolicy: Owner

  data:
    - secretKey: value
      remoteRef:
        key: dev-cloudflare-api-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  refreshInterval: 5h

  secretStoreRef:
    kind: ClusterSecretStore
    name: parameterstore

  target:
    creationPolicy: Owner

  data:
    - secretKey: cloudflare_api_key
      remoteRef:
        key: dev-cloudflare-api-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: external-dns
spec:
  refreshInterval: 5h

  secretStoreRef:
    kind: ClusterSecretStore
    name: parameterstore

  target:
    creationPolicy: Owner

  data:
    - secretKey: cloudflare_api_key
      remoteRef:
        key: dev-cloudflare-api-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: telegram-token
  namespace: flux-system
spec:
  refreshInterval: 5h

  secretStoreRef:
    kind: ClusterSecretStore
    name: parameterstore

  target:
    creationPolicy: Owner

  data:
    - secretKey: token
      remoteRef:
        key: telegram-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin4-creds
  namespace: pgadmin4
spec:
  refreshInterval: 5h

  secretStoreRef:
    kind: ClusterSecretStore
    name: parameterstore

  target:
    creationPolicy: Owner

  data:
    - secretKey: password
      remoteRef:
        key: pgadmin4-creds
